#Adds the option to go to eg. http://localhost:8080/actuator/health for seeing the running configuration
#see https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  h2:
    console:
      enabled: true

hapi:
  fhir:
    enable_repository_validating_interceptor: false
    enforce_referential_integrity_on_write: false

com:
  essaid:
    fhir:
      hapi:
        extensions:
          provider-class-names:
            - com.essaid.fhir.hapi.ext.provider.util.UtilsHapiProvider
            - com.essaid.fhir.hapi.ext.provider.CodeSystemConceptSearchOperation