spring:
  main:
    allow-bean-definition-overriding: true

com:
  essaid:
    hapi-ext:
      restful-server:
        configurers:
          enabled: true
          type: context # Set to "map" to use the mapping configuration below, or "context" (the default) to look up all implementations in the context
          # The implementations of: com.essaid.fhir.hapi.ext.server.IRestfulServerConfigurer
          map: {}
            # Examples
            # someKey: class:some.full.class.Name  (notice the "class:" prefix). This will load the class from the spring context
            # someOtherKey: bean:someBeanName  (notice the "bean:" prefix). This will load the named bean from the spring context
      index:
        analysis:
          apply-defaults: true
          configurers:
            enabled: true
            type: context # Above comments apply here as well.
            # The implementations of:
            # org.hibernate.search.backend.lucene.analysis.LuceneAnalysisConfigurer
            # org.hibernate.search.backend.elasticsearch.analysis.ElasticsearchAnalysisConfigurer
            # You need to enable the appropriate ones in your context based on your indexing backend.
            # Or use the "map" mode to control by configuration
            map: {} # Above comments apply here as well.
        mapping:
          configurers:
            enabled: true
            type: context # map to use the mapping configuration, or 'context' (the default) to look up all implementations in the context
            # The implementations of
            # org.hibernate.search.mapper.orm.mapping.HibernateOrmSearchMappingConfigurer
            map: {} # Above comments apply here as well.
      entity-manager-factory:
        process-properties: true
        default-properties: {}
        override-properties:
          # Do not change this unless you understand how the extension mechanism works.
          # You can override other properties if needed but these two are key to the extension functionality
          "hibernate.search.backend.analysis.configurer": class:com.essaid.fhir.hapi.ext.HapiExtensionConfiguration
          "hibernate.search.mapping.configurer": class:com.essaid.fhir.hapi.ext.HapiExtensionConfiguration